/**
 * Generate clean ATS-friendly PDF and DOCX from rewritten resume JSON.
 */
import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import PDFDocument from "pdfkit";
import type { ResumeSection } from "./rewriteEngine";

export type ResumeJson = {
  name?: string;
  contact?: { email?: string; phone?: string; linkedin?: string; location?: string };
  summary?: string;
  sections: ResumeSection[];
};

function strip(s: string): string {
  return s.replace(/\u2014|\u2013/g, ", ").replace(/  +/g, " ");
}

function contactLine(c?: ResumeJson["contact"]): string {
  if (!c) return "";
  return [c.email, c.phone, c.linkedin, c.location].filter(Boolean).join(" | ");
}

export async function generatePdf(json: ResumeJson): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "LETTER", margins: { top: 54, bottom: 54, left: 54, right: 54 } });
      const chunks: Buffer[] = [];
      doc.on("data", (c: Buffer) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header: name + contact
      if (json.name) {
        doc.font("Helvetica-Bold").fontSize(20).fillColor("#1a1a2e").text(strip(json.name), { align: "left" });
      }
      const cl = contactLine(json.contact);
      if (cl) {
        doc.moveDown(0.2);
        doc.font("Helvetica").fontSize(10).fillColor("#5b5b6c").text(strip(cl));
      }
      doc.moveDown(0.5);
      doc.strokeColor("#d4a843").lineWidth(1.5).moveTo(54, doc.y).lineTo(558, doc.y).stroke();
      doc.moveDown(0.5);

      const writeHeading = (h: string) => {
        doc.font("Helvetica-Bold").fontSize(12).fillColor("#1a1a2e").text(strip(h.toUpperCase()), { characterSpacing: 1 });
        doc.moveDown(0.2);
      };
      const writeBody = (text: string, bullet: boolean) => {
        doc.font("Helvetica").fontSize(11).fillColor("#1a1a2e");
        if (bullet) {
          doc.text(strip(text), { indent: 14, paragraphGap: 2, bulletIndent: 14, lineGap: 1 });
        } else {
          doc.text(strip(text), { paragraphGap: 4, lineGap: 1 });
        }
      };

      if (json.summary) {
        writeHeading("Professional Summary");
        writeBody(json.summary, false);
        doc.moveDown(0.4);
      }
      for (const sec of json.sections) {
        writeHeading(sec.heading);
        for (const item of sec.body) {
          const cleanItem = item.replace(/^[-•]\s+/, "");
          writeBody("• " + cleanItem, true);
        }
        doc.moveDown(0.4);
      }
      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

export async function generateDocx(json: ResumeJson): Promise<Buffer> {
  const para = (text: string, opts: { bold?: boolean; size?: number; color?: string; align?: (typeof AlignmentType)[keyof typeof AlignmentType]; bullet?: boolean; spaceAfter?: number } = {}) =>
    new Paragraph({
      alignment: opts.align,
      spacing: { after: opts.spaceAfter ?? 80 },
      bullet: opts.bullet ? { level: 0 } : undefined,
      children: [
        new TextRun({
          text: strip(text),
          bold: opts.bold,
          size: opts.size ?? 22, // half-points; 22 = 11pt
          color: opts.color ?? "1a1a2e",
          font: "Calibri",
        }),
      ],
    });

  const heading = (text: string) =>
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
      children: [
        new TextRun({
          text: strip(text.toUpperCase()),
          bold: true,
          color: "1a1a2e",
          size: 24,
          font: "Calibri",
        }),
      ],
    });

  const children: Paragraph[] = [];
  if (json.name) {
    children.push(
      new Paragraph({
        spacing: { after: 60 },
        children: [
          new TextRun({ text: strip(json.name), bold: true, size: 36, color: "1a1a2e", font: "Calibri" }),
        ],
      }),
    );
  }
  const cl = contactLine(json.contact);
  if (cl) children.push(para(cl, { color: "5b5b6c", size: 20, spaceAfter: 200 }));

  if (json.summary) {
    children.push(heading("Professional Summary"));
    children.push(para(json.summary));
  }
  for (const sec of json.sections) {
    children.push(heading(sec.heading));
    for (const item of sec.body) {
      const cleanItem = item.replace(/^[-•]\s+/, "");
      children.push(para(cleanItem, { bullet: true }));
    }
  }

  const doc = new Document({
    creator: "EO50 Resume Rewriter",
    title: json.name ? `${strip(json.name)} Resume` : "Resume",
    description: "Generated by EO50 Resume Rewriter",
    sections: [{ properties: {}, children }],
  });

  return await Packer.toBuffer(doc);
}
